### ISSUE TITLE
Chiarimento: campo "Valore"

### ISSUE THREAD

**Issue by Trainax** [DataEnthusiast84/CoViD-19-Italy#1]
Ho notato adesso questa collezione di dati e mi sembra interessante. Che cosa rappresenta il campo "Valore"?
Propongo inoltre di cambiare alcuni campi e far diventare il DB così:

| Data          | Sesso         | Età           | Paese di origine (Nazione)   | Regione di origine | Comune (se conosciuto) | Stato (confirmed, dead, recovered) | Complicanze (facoltativo) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 31/01/2020  | M  | 67 | Cina | Wuhan | |  Confirmed
| 31/01/2020  | F  | 66 | Cina | Wuhan | |  Confirmed
| 22/02/2020  | M  | 38 | Italia | Lombardia | Codogno | Confirmed |

Secondo me così si renderebbe il DB più organizzato. Cosa ne pensi?

**Comment by DataEnthusiast84** [comment]
Ciao @Trainax e grazie per il commento! 

Ti chiedo scusa per il ritardo con cui ti rispondo.

Il valore era inteso come il numero di pazienti (numerosità). Questo per definire gruppi di pazienti che non possono essere registrati singolarmente..Mi piacerebbe in realtà creare una sorta di DB "nominativo" ma i dati purtroppo scarseggiano e le fonti ufficiali non sono poi così dettagliate.

Un focus molto interessante è stato fatto dall'utente @marinog82 in questa discussione:

https://github.com/CSSEGISandData/COVID-19/issues/119

Il tuo suggerimento è ben accolto! Purtroppo ad oggi ho notevole difficoltà nel reperimento dei dati

**Comment by Trainax** [comment]
Ciao, ho notato che negli scorsi giorni sono nate molte repo per soddisfare l'esigenza di tener traccia degli avvenimenti che stanno accadendo. [Qui](https://github.com/pcm-dpc/COVID-19) ad esempio c'è la repo ufficiale della Protezione Civile, quindi magari puoi guardare quei dati per poter tenere aggiornata questa repo.

Ti ringrazio per aver fugato il mio dubbio riguardo al campo "Valore".

Chiudo questa issue perché il mio dubbio è stato risolto.
